apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
    replicas: 2
    template:
      metadata:
        labels:
          app: myapp
      spec:
        containers:
        - name: myapp
          image: nanajanashie/arcocd-app:1.0 # put the image you want for deploy
          ports:
          - containerPort: 8080